/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e3cdd766-d018-48e6-b677-62bebb585a68

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int analogica;
  bool ligar;
  bool ligar1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define LED 2 
#define portao 13
#define pressao 35
int analogica_pressao = 0;

//#define Portao 13

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  //Define pino como saida
  pinMode(LED, OUTPUT);
  
  pinMode(portao, OUTPUT);

  //Define pino como saida
  //pinMode(Portao, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here

//Leitura sensor de pressão 
analogica_pressao = analogRead(analogica);
analogica = map(analogica_pressao, 0, 4095,0,1023);

}

/*
  Since Ligar is READ_WRITE variable, onLigarChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLigarChange()  {
  // Add your code here to act upon Ligar change
  digitalWrite(LED, ligar);
  //digitalWrite(Portao, garagem);

}


/*
  Since Portao is READ_WRITE variable, onPortaoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPortaoChange()  {
  // Add your code here to act upon Portao change
  //digitalWrite(Portao, garagem);
}






/*
  Since Garagem is READ_WRITE variable, onGaragemChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGaragemChange()  {
  //digitalWrite(LED, ligar);
  // Add your code here to act upon Garagem change
}


/*
  Since Ligar1 is READ_WRITE variable, onLigar1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLigar1Change()  {
  // Add your code here to act upon Ligar1 change
  digitalWrite(portao, ligar1);
}